services:
  chromium:
    build: 
      context: .
      args:
        DISTRO_CODENAME: bookworm
      tags:
        - quay.io/inviqa_images/chromium:latest${TAG_SUFFIX:-}
    image: quay.io/inviqa_images/chromium:bookworm${TAG_SUFFIX:-}

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    links:
      - chromium:chromium
    profiles:
      - test
